resources:
  - configmaps/dataset-service-config.yaml
  - configmaps/postgres-init-configmap.yaml
  - dataset-service/dataset-service-deployment.yaml
  - dataset-service/dataset-service-service.yaml
  - helm/Chart.yaml
  - helm/values.yaml
  - opensearch/opensearch-deployment.yaml
  - opensearch/opensearch-service.yaml
  - opensearch/opensearch-pvc.yaml
  - postgres/postgres-deployment.yaml
  - postgres/postgres-service.yaml
  - postgres/postgres-pvc.yaml
  - secrets/dataset-service-secrets.yaml
  - secrets/postgres-secrets.yaml
  - namespace.yaml