# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from schematic_api.models.base_model_ import Model
from schematic_api import util


class ComponentsInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """ComponentsInner - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ComponentsInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Components_inner of this ComponentsInner.  # noqa: E501
        :rtype: ComponentsInner
        """
        return util.deserialize_model(dikt, cls)
